"""Modeling utilities: primitives, CSG helpers, and path abstractions."""

from __future__ import annotations

from .transform import rotate, translate, scale, resize, mirror, multmatrix, rotate_euler
from .primitives import (
    make_box,
    make_cone,
    make_cylinder,
    make_nhedron,
    make_ngon,
    make_polyhedron,
    make_prism,
    make_sphere,
    make_torus,
)
from .drawing2d import (
    Arc2D,
    Bezier2D,
    Line2D,
    Path2D,
    Profile2D,
    round_corners,
    round_path,
    make_circle,
    make_ngon as make_ngon_2d,
    make_polygon,
    make_polyline,
    make_rect,
)
from .extrude import linear_extrude, rotate_extrude
from .loft import loft, loft_profiles
from .morph import morph, morph_profiles
from .path3d import Arc3D, Bezier3D, Line3D, Path3D
from .csg import boolean_union, boolean_difference, boolean_intersection, union_meshes
from .paths import Path
from .group import MeshGroup, group
from .ops import offset, hull, minkowski
from .heightmap import heightmap, displace_heightmap
from .text import make_text, text, text_profiles
from impression.mesh_quality import MeshQuality
from .threading import (
    FIT_PRESETS,
    InvalidFitSpec,
    InvalidThreadSpec,
    MeshBudgetExceeded,
    ThreadFitPreset,
    ThreadMeshEstimate,
    ThreadSpec,
    ThreadingError,
    apply_fit,
    estimate_mesh_cost,
    lookup_standard_thread,
    make_external_thread,
    make_hex_nut,
    make_internal_thread,
    make_round_nut,
    make_runout_relief,
    make_tapped_hole_cutter,
    make_threaded_rod,
    clear_thread_cache,
    paired_fit,
    validate_thread,
)

__all__ = [
    "make_box",
    "make_cylinder",
    "make_cone",
    "make_ngon",
    "make_nhedron",
    "make_polyhedron",
    "make_prism",
    "make_sphere",
    "make_torus",
    "Arc2D",
    "Bezier2D",
    "Line2D",
    "Path2D",
    "Profile2D",
    "round_corners",
    "round_path",
    "make_rect",
    "make_circle",
    "make_ngon_2d",
    "make_polygon",
    "make_polyline",
    "Line3D",
    "Arc3D",
    "Bezier3D",
    "Path3D",
    "linear_extrude",
    "rotate_extrude",
    "morph",
    "morph_profiles",
    "loft",
    "loft_profiles",
    "boolean_union",
    "boolean_difference",
    "boolean_intersection",
    "union_meshes",
    "Path",
    "MeshGroup",
    "group",
    "rotate",
    "translate",
    "scale",
    "resize",
    "mirror",
    "multmatrix",
    "rotate_euler",
    "offset",
    "hull",
    "minkowski",
    "heightmap",
    "displace_heightmap",
    "make_text",
    "text",
    "text_profiles",
    "FIT_PRESETS",
    "InvalidFitSpec",
    "InvalidThreadSpec",
    "MeshBudgetExceeded",
    "MeshQuality",
    "ThreadFitPreset",
    "ThreadMeshEstimate",
    "ThreadSpec",
    "ThreadingError",
    "apply_fit",
    "estimate_mesh_cost",
    "lookup_standard_thread",
    "make_external_thread",
    "make_hex_nut",
    "make_internal_thread",
    "make_round_nut",
    "make_runout_relief",
    "make_tapped_hole_cutter",
    "make_threaded_rod",
    "clear_thread_cache",
    "paired_fit",
    "validate_thread",
]
